name: Build CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Job 1 is running"
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Job 2 is running"