name: Build CI
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Job 2 is running"